{% set name = "nglview" %}
{% set version = "2.7.7.dev0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://github.com/ericpre/nglview/archive/refs/heads/master.zip
  sha256: dd16527c49e67cdd53b345768da2ba421a04d5cdfd85d1e373260482baa566fd


build:
  noarch: python
  number: {{ build_number }}

outputs:
  - name: {{ name|lower }}
    build:
      number: {{ build_number }}
      noarch: python  
    script: build_nglview.sh
    requirements:
      host:
        - ipywidgets
        - pip
        - python >=3.6
        - notebook
        - numpy
      run:
        - ipywidgets
        - python >=3.6
        - notebook
        - numpy
    test:
      imports:
        - nglview

  - name: nglview-js-widgets
    build:
      number: {{ build_number }}
      noarch: python
    script: build_js_widgets.sh
    requirements:
      host:
        - ipywidgets
        - jupyterlab
        - jupyter-packaging
        - {{ pin_subpackage('nglview', exact=True) }}
        - numpy
        - nodejs
        - pip
        - python >=3.6
      run:
        - ipywidgets
        - jupyterlab
        - {{ pin_subpackage('nglview', exact=True) }}
        - numpy
        - python >=3.6

    test:
      commands:
        - jupyter labextension list 2>&1 | grep -ie "nglview-js-widgets.*OK"

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
